const portfolioData = [
  {
    image: "admin.7c104f30.png",
    alt: "admin_panel",
    purpose: "school",
    focus: "skill test",
    technology: "html, scss, javascript",
    responsiveness: "desktop, tablet, mobile",
    repository: "github",
    repoLink: "https://github.com/kherma/project-01-admin-panel",
    deploy: "github pages",
    depoLink: "https://kherma.github.io/project-01-admin-panel/",
  },
  {
    image: "restaurant.e51a5fbd.png",
    alt: "restaurant",
    purpose: "school",
    focus: "skill test",
    technology: "html, scss, javascript",
    responsiveness: "desktop, tablet",
    repository: "github",
    repoLink: "https://github.com/kherma/school-06-project-pizzeria",
    deploy: "Heroku",
    depoLink:
      "https://murmuring-wave-46799.herokuapp.com/?date=2020-12-04&hour=12&people=1&hours=1&phone=&address=#/home",
  },
  {
    image: "api.77d6c145.png",
    alt: "mapty",
    purpose: "course",
    focus: "oop, api",
    technology: "javascript, geolocation",
    responsiveness: "desktop, tablet",
    repository: "github",
    repoLink: "https://github.com/kherma/practice-12-mapty-oop",
    deploy: "Netlify",
    depoLink: "https://loving-nightingale-601569.netlify.app/",
  },
  {
    image: "bankist.7ee588a2.png",
    alt: "bankist",
    purpose: "course",
    focus: "arrays, date & time",
    technology: "html, scss, javascript",
    responsiveness: "desktop",
    repository: "github",
    repoLink: "https://github.com/kherma/practice-09-bankist-date-time",
    deploy: "Netlify",
    depoLink: "https://hopeful-ramanujan-a0f4c6.netlify.app/",
  },
  {
    image: "blog.71a5819c.png",
    alt: "blog",
    purpose: "school",
    focus: "data structure",
    technology: "html, scss, javascript",
    responsiveness: "desktop",
    repository: "github",
    repoLink: "https://github.com/kherma/school-05-javascript-blog",
    deploy: "github pages",
    depoLink: "https://kherma.github.io/school-05-javascript-blog/",
  },
  {
    image: "dom.651b1946.png",
    alt: "bankist_dom",
    purpose: "course",
    focus: "dom manipulation",
    technology: "html, scss, javascript",
    responsiveness: "desktop",
    repository: "github",
    repoLink: "https://github.com/kherma/practice-11-bankist-advanced-dom",
    deploy: "Nettlify",
    depoLink: "https://cranky-curran-3e989d.netlify.app/",
  },
  {
    image: "game_1.13edd534.png",
    alt: "rock_paper_scissors",
    purpose: "school",
    focus: "intro to javascript",
    technology: "html, scss, javascript",
    responsiveness: "desktop",
    repository: "github",
    repoLink: "https://github.com/kherma/school-04-javascript-prework",
    deploy: "github pages",
    depoLink: "https://kherma.github.io/school-04-javascript-prework/",
  },
  {
    image: "game_2.cee0bbe3.png",
    alt: "dice_game",
    purpose: "course",
    focus: "skill test",
    technology: "intro to javascript",
    responsiveness: "desktop, tablet",
    repository: "github",
    repoLink: "https://github.com/kherma/practice-03-dice-game-dom",
    deploy: "github pages",
    depoLink: "https://kherma.github.io/practice-03-dice-game-dom/",
  },
  {
    image: "grid.d4bc39dd.png",
    alt: "news_grid",
    purpose: "course",
    focus: "practice grid",
    technology: "html, css",
    responsiveness: "desktop, tablet, mobile, small, landscape",
    repository: "github",
    repoLink: "https://github.com/kherma/practice-07-grid",
    deploy: "Netlify",
    depoLink: "https://determined-chandrasekhar-9a7b2f.netlify.app/",
  },
  {
    image: "hania.861d9141.png",
    alt: "how_i_met_your_hania",
    purpose: "personal",
    focus: "fun",
    technology: "html, scss, javascript",
    responsiveness: "desktop, tablet, mobile, small, landscape",
    repository: "github",
    repoLink: "https://github.com/kherma/side-03-how-i-met-your-hania",
    deploy: "Heroku",
    depoLink: "http://haniaambroziewiczisajerk.herokuapp.com/",
  },
  {
    image: "sass.dd9b4d93.png",
    alt: "portfolio_website",
    purpose: "course",
    focus: "practice sass",
    technology: "html, scss, javascript",
    responsiveness: "desktop, tablet, mobile, small, landscape",
    repository: "github",
    repoLink: "https://github.com/kherma/practice-08-sass",
    deploy: "Netlify",
    depoLink: "https://stoic-cray-f8ac53.netlify.app/index.html",
  },
  {
    image: "sheet.89aec90e.png",
    alt: "git_sheet",
    purpose: "personal",
    focus: "git, github",
    technology: "n/a",
    responsiveness: "n/a",
    repository: "n/a",
    repoLink: "n/a",
    deploy: "n/a",
    depoLink: "n/a",
  },
];

export default portfolioData;
